services:
  # copilot-gpt4-service:
  #   image: aaamoon/copilot-gpt4-service:latest
  #   container_name: copilot-gpt4-service
  #   restart: always
  #   ports:
  #     - "10100:8080"
  #   environment:
  #     - COPILOT_TOKEN=${GITHUB_COPILOT_PLUGIN_KEY}
  #     - SUPER_TOKEN=${LOBE_CHAT_ACCESS_CODE}
  #     - ENABLE_SUPER_TOKEN=true
  #     - RATE_LIMIT=200

  network-service:
    image: alpine
    container_name: lobe-network
    ports:
      - ${MINIO_PORT:-9000}:${MINIO_PORT:-9000} # MinIO API
      - 9001:9001 # MinIO Console
      - ${LOGTO_PORT:-3001}:${LOGTO_PORT:-3001} # Logto
      - 3002:3002 # Logto Admin
      - ${LOBE_PORT:-3210}:3210 # LobeChat
    command: tail -f /dev/null
    networks:
      - lobe-network

  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=${LOBE_DB_NAME:-lobechat}
      - POSTGRES_PASSWORD=${LOBE_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - lobe-network

  minio:
    image: minio/minio
    container_name: lobe-minio
    network_mode: "service:network-service"
    volumes:
      - "./s3_data:/etc/minio/data"
    environment:
      - MINIO_ROOT_USER=${LOBE_MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${LOBE_MINIO_ROOT_PASSWORD}
      - MINIO_API_CORS_ALLOW_ORIGIN=http://localhost:${LOBE_PORT:-3210}
    restart: always
    command: >
      server /etc/minio/data --address ":${MINIO_PORT:-9000}" --console-address ":9001"

  logto:
    image: svhd/logto:1.20.0
    container_name: lobe-logto
    network_mode: "service:network-service"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - TRUST_PROXY_HEADER=1
      - PORT=${LOGTO_PORT:-3001}
      - DB_URL=postgresql://postgres:${LOBE_POSTGRES_PASSWORD}@postgresql:5432/logto
      - ENDPOINT=http://localhost:${LOGTO_PORT:-3001}
      - ADMIN_ENDPOINT=http://localhost:3002
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]

  lobe-chat:
    # depends_on:
    #   - copilot-gpt4-service
    # image: lobehub/lobe-chat
    image: lobehub/lobe-chat-database:latest
    container_name: lobe-chat-database
    restart: always
    network_mode: 'service:network-service'
    env_file: lobe-chat.env
    depends_on:
      postgresql:
        condition: service_healthy
      network-service:
        condition: service_started
      minio:
        condition: service_started
      logto:
        condition: service_started

volumes:
  data:
    driver: local
  s3_data:
    driver: local

networks:
  lobe-network:
    driver: bridge
