version: "3.8"

services:
  # copilot-gpt4-service:
  #   image: aaamoon/copilot-gpt4-service:latest
  #   container_name: copilot-gpt4-service
  #   restart: always
  #   ports:
  #     - "10100:8080"
  #   environment:
  #     - COPILOT_TOKEN=${GITHUB_COPILOT_PLUGIN_KEY}
  #     - SUPER_TOKEN=${LOBE_CHAT_ACCESS_CODE}
  #     - ENABLE_SUPER_TOKEN=true
  #     - RATE_LIMIT=200

  lobe-chat:
    # depends_on:
    #   - copilot-gpt4-service
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - "10101:3210"
    environment:
      # If you don't choose hack
      - HTTPS_PROXY=${LOBE_CLIENT_HTTP_PROXY}
      - OPENAI_API_KEY=${LOBE_CHAT_OPENAI_TOKEN}
      - OPENAI_PROXY_URL=${LOBE_CHAT_OPENAI_PROXY_URL}

      # hack github copilot to gpt4
      # - OPENAI_MODEL_LIST=-all,+gpt-3.5-turbo,+gpt-4
      # - OPENAI_API_KEY=${LOBE_CHAT_ACCESS_CODE}
      # - OPENAI_PROXY_URL=http://copilot-gpt4-service:8080/v1
      # - ACCESS_CODE=${LOBE_CHAT_ACCESS_CODE:-lobe66}

      # openai
      - DEFAULT_AGENT_CONFIG=provider=ollama;model=qwen2:7b;enableHistoryCount=true;historyCount=5;params.max_tokens=8000;fetchOnClient=true;

      # - SYSTEM_AGENT=provider=ollama;model=qwen2:7b;
      - SYSTEM_AGENT=topic=ollama/qwen2:7b,agentMeta=ollama/qwen2:7b,queryRewrite=ollama/qwen2:7b,translation=ollama/qwen2:7b

      # google gemini
      - GOOGLE_API_KEY=${GOOGLE_GEMINI_API_KEY}
      # ollama
      - OLLAMA_PROXY_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL_LIST=-all,+qwen2:7b
      # 智谱AI
      - ZHIPU_API_KEY=${OFFICIAL_ZHIPU_TOKEN}
      # 付费 qwen
      - QWEN_API_KEY=${ALIYUN_DASHSCOPE_API_KEY}
